name: Beta Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM UTC

jobs:
  beta-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708
          accept-android-sdk-licenses: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > app/keystore.jks

      - name: Create keystore.properties
        run: |
          cat > keystore.properties << EOF
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=keystore.jks
          EOF

      - name: Create Google Play service account key
        run: |
          echo "${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}" > app/play-service-account.json

      - name: Generate version
        run: |
          VERSION_NAME="1.0.0-beta.$(date +%Y%m%d)"
          VERSION_CODE=$(date +%Y%m%d%H)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV

      - name: Build Release Bundle
        run: |
          ./gradlew bundleRelease \
            -PversionName="${{ env.VERSION_NAME }}" \
            -PversionCode="${{ env.VERSION_CODE }}"

      - name: Upload to Beta Track
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: app/play-service-account.json
          packageName: com.matrixy.composeexperiments
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: beta
          status: completed
          whatsNewDirectory: distribution/whatsnew

      - name: Clean up sensitive files
        if: always()
        run: |
          rm -f app/keystore.jks
          rm -f keystore.properties
          rm -f app/play-service-account.json